apiVersion: apps/v1 
kind: Deployment    
metadata:
  name: minio-deployment 
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: minio
  replicas: {{.Values.replicas}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-pvc
          volumeClaimTemplates:
            claimName: minio-pvc
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_USER
              value: {{.Values.minio_root_user}}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: secret
                    key: minio_root_password
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-pvc
              mountPath: "/data"